# Site settings
title: M-Lab
email: support@measurementlab.net
baseurl: ""

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock